name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  darwin:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: build-darwin
        run: make build-darwin VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      - name: zip
        run: cd dist && zip -r Prosper-darwin.zip Prosper.app
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Prosper-darwin.zip

  windows:
    runs-on: windows-latest
    needs: darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: build-windows
        shell: bash
        run: make build-windows VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      - name: zip
        run: cd dist && Compress-Archive Prosper.exe Prosper-windows.zip
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Prosper-windows.zip

  linux:
    runs-on: ubuntu-latest
    needs: darwin
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: deps
        run: sudo apt install -y xorg-dev
      - name: build-linux
        run: make build-linux VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Prosper-linux.tar.xz
