name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1

  darwin:
    runs-on: macos-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: build-darwin
        run: make build-darwin VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      - name: zip
        run: cd dist && zip -r Prosper-darwin-amd64.zip Prosper.app
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/Prosper-darwin-amd64.zip
            dist/bin-darwin-amd64.gz

  windows:
    runs-on: windows-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: install gzip
        run: choco install gzip
      - name: install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: build-windows
        shell: bash
        run: make build-windows VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      - name: zip
        run: cd dist && Compress-Archive Prosper.exe Prosper-windows-amd64.zip
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/Prosper-windows-amd64.zip
            dist/bin-windows-amd64.gz

  linux:
    runs-on: ubuntu-latest
    needs: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - name: install fyne
        run: go install fyne.io/fyne/v2/cmd/fyne@latest
      - name: deps
        run: |
          sudo apt update
          sudo apt install -y xorg-dev
      - name: build-linux
        run: make build-linux VERSION=$(echo ${GITHUB_REF/refs\/tags\/v/})
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/Prosper-linux-amd64.tar.xz
            dist/bin-linux-amd64.gz
